spring.application.name=delivery-app-api

#mongodb configuration
spring.data.mongodb.uri=mongodb://localhost:27017/foodies

#aws s3 configuration
aws.access.key=${AWS_ACCESS_KEY}
aws.secret.key=${AWS_SECRET_KEY}
aws.region=ap-south-1

aws.s3.bucketname=foodies-food10


jwt.secret.key=${JWT_SECRET_KEY}

#razorpay configuration

razorpay_key=${RAZORPAY_KEY}
razorpay_secret=${RAZORPAY_SECRET}